# -*- coding: utf-8 -*-
"""1 - Problem (Task)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aF8i-CB-9HZCYlVMVdUCpY7qE8QjOsQY

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement s^c of s.
"""